### ISSUE TITLE
Broken Colab Link

### ISSUE THREAD

**Issue by nikhilkomakula** [lucifertrj/Awesome-RAG#1]
Hello,

First of all, Great resources! Thanks for sharing and making it available for everyone.

The Colab link to "Evaluate LLMs" seems to be broken. Could you please fix it.

Also, is there a YouTube link for the same explaining Ragas?

Thanks.

**Comment by Pratham-taneja** [comment]
yes I will fix it asap and for sure if i can find the link explaining Ragas I will add it to a notebook file in the repro itself
Btw thanks for checking out my work.
